version: 2.1

workflows:
  test:
    jobs:
      - build-all
      - test-windows:
          name: .NET Framework 4.7.1 - Windows
          build-target-framework: net471
          test-target-framework: net471
          requires:
            - build-all





orbs:
  windows: circleci/windows@2.2.0

jobs:
  test:
    description: Setup and run application tests
    executor:
      name: windows/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - nuget-packages-v1-{{ checksum "CapaPresentaciones/CapaPresentaciones.csproj" }}
      - run:
          name: "Install nuget dependencies"
          command: nuget restore
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
      - save_cache:
          paths:
            - C:\Users\circleci.nuget\packages
          key: nuget-packages-v1-{{ checksum "CapaPresentaciones/CapaPresentaciones.csproj" }}
      - run:
          name: "Run build step"
          command: dotnet.exe publish -c Release -r win10-x64
      - run:
          name: "Run Application Tests"
          command: dotnet.exe test PruebasUnitarias/PruebasUnitarias.csproj -v n --results-directory:test_coverage --collect:"Code Coverage"
      - store_artifacts:
          path: C:\Users\circleci\project\test_coverage
  build:
    description: Build application with Release configuration
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Build Application according to some given configuration"
          command: dotnet.exe build --configuration Release
workflows:
  test_and_build:
    jobs:
      - test
      - build:
          requires:
            - test