version: 2.1

orbs:
  windows: circleci/windows@2.2.0

jobs:
  test:
    description: Setup and run application tests
    executor:
      name: windows/default
    environment:
      TESTFRAMEWORK: net461
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "CapaPresentaciones/CapaPresentaciones.csproj" }}-{{ checksum "PruebasUnitarias/PruebasUnitarias.csproj" }}
      - run:
          name: "Install project dependencies"
          command: dotnet restore
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "CapaPresentaciones/CapaPresentaciones.csproj" }}-{{ checksum "PruebasUnitarias/PruebasUnitarias.csproj" }}
      - run:
          name: "Print Working Directory"
          command: pwd
      - run:
          name: "build SDK for .net Framework 4.6.1"
          command: dotnet build project/CapaPresentaciones -f net461
      - run:
          name: "Run Application Tests"
          command: dotnet test PruebasUnitarias/PruebasUnitarias.csproj -f net461
      - store_artifacts:
          path: C:\Users\circleci\project\test_coverage
workflows:
  test_project:
    jobs:
      - test
